name: Deploy Blog to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup SSH ğŸ”
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 ğŸš€
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Ganti dengan path sesuai repo kamu
            cd ~/Web-blog-AWs
            sudo git pull origin main
            sudo cp -r * /usr/share/nginx/html/
            sudo systemctl restart nginx
          EOF
